#pragma once
#include "wasm.h"

WASM_IMPORT(int, JS_isinf, (double));
WASM_IMPORT(int, JS_isnan, (double));

WASM_IMPORT(double, JS_acos, (double));
WASM_IMPORT(double, JS_acosh, (double));
WASM_IMPORT(double, JS_asin, (double));
WASM_IMPORT(double, JS_asinh, (double));
WASM_IMPORT(double, JS_atan, (double));
WASM_IMPORT(double, JS_atan2, (double, double));
WASM_IMPORT(double, JS_atanh, (double));
WASM_IMPORT(double, JS_cbrt, (double));
WASM_IMPORT(double, JS_ceil, (double));
// double JS_copysign(double, double);
WASM_IMPORT(double, JS_cos, (double));
WASM_IMPORT(double, JS_cosh, (double));
// double JS_erf(double);
// double JS_erfc(double);
WASM_IMPORT(double, JS_exp, (double));
WASM_IMPORT(double, JS_exp2, (double));
WASM_IMPORT(double, JS_expm1, (double));
WASM_IMPORT(double, JS_fabs, (double));
WASM_IMPORT(double, JS_fdim, (double, double));
WASM_IMPORT(double, JS_floor, (double));
// double JS_fma(double, double, double);
WASM_IMPORT(double, JS_fmax, (double, double));
WASM_IMPORT(double, JS_fmin, (double, double));
WASM_IMPORT(double, JS_fmod, (double, double));
// double JS_frexp(double, int *);
WASM_IMPORT(double, JS_hypot, (double, double));
// int JS_ilogb(double);
WASM_IMPORT(double, JS_ldexp, (double, int));
// double JS_lgamma(double);
// long long JS_llrint(double);
// long long JS_llround(double);
WASM_IMPORT(double, JS_log, (double));
WASM_IMPORT(double, JS_log10, (double));
WASM_IMPORT(double, JS_log1p, (double));
WASM_IMPORT(double, JS_log2, (double));
// double JS_logb(double);
// long JS_lrint(double);
// long JS_lround(double);
WASM_IMPORT(double, JS_modf, (double, double *));
WASM_IMPORT(double, JS_nan, (const char *));
// double JS_nearbyint(double);
// double JS_nextafter(double, double);
// double JS_nexttoward(double, long double);
WASM_IMPORT(double, JS_pow, (double, double));
// double JS_remainder(double, double);
// double JS_remquo(double, double, int *);
// double JS_rint(double);
WASM_IMPORT(double, JS_round, (double));
// double JS_scalbln(double, long);
// double JS_scalbn(double, int);
WASM_IMPORT(double, JS_sin, (double));
WASM_IMPORT(double, JS_sinh, (double));
WASM_IMPORT(double, JS_sqrt, (double));
WASM_IMPORT(double, JS_tan, (double));
WASM_IMPORT(double, JS_tanh, (double));
// double JS_tgamma(double);
WASM_IMPORT(double, JS_trunc, (double));


WASM_IMPORT(float, JS_acosf, (float));
WASM_IMPORT(float, JS_acoshf, (float));
WASM_IMPORT(float, JS_asinf, (float));
WASM_IMPORT(float, JS_asinhf, (float));
WASM_IMPORT(float, JS_atanf, (float));
WASM_IMPORT(float, JS_atan2f, (float, float));
WASM_IMPORT(float, JS_atanhf, (float));
WASM_IMPORT(float, JS_cbrtf, (float));
WASM_IMPORT(float, JS_ceilf, (float));
WASM_IMPORT(float, JS_cosf, (float));
WASM_IMPORT(float, JS_coshf, (float));
WASM_IMPORT(float, JS_expf, (float));
WASM_IMPORT(float, JS_exp2f, (float));
WASM_IMPORT(float, JS_expm1f, (float));
WASM_IMPORT(float, JS_fabsf, (float));
WASM_IMPORT(float, JS_fdimf, (float, float));
WASM_IMPORT(float, JS_floorf, (float));
WASM_IMPORT(float, JS_fmaxf, (float, float));
WASM_IMPORT(float, JS_fminf, (float, float));
WASM_IMPORT(float, JS_fmodf, (float, float));
WASM_IMPORT(float, JS_hypotf, (float, float));
WASM_IMPORT(float, JS_ldexpf, (float, int));
WASM_IMPORT(float, JS_logf, (float));
WASM_IMPORT(float, JS_log10f, (float));
WASM_IMPORT(float, JS_log1pf, (float));
WASM_IMPORT(float, JS_log2f, (float));
WASM_IMPORT(float, JS_modff, (float, float *));
WASM_IMPORT(float, JS_nanf, (const char *));
WASM_IMPORT(float, JS_powf, (float, float));
WASM_IMPORT(float, JS_roundf, (float));
WASM_IMPORT(float, JS_sinf, (float));
WASM_IMPORT(float, JS_sinhf, (float));
WASM_IMPORT(float, JS_sqrtf, (float));
WASM_IMPORT(float, JS_tanf, (float));
WASM_IMPORT(float, JS_tanhf, (float));
WASM_IMPORT(float, JS_truncf, (float));
