#pragma once
#include "wasm.h"

WASM_IMPORT(double, acos, double);
WASM_IMPORT(double, acosh, double);
WASM_IMPORT(double, asin, double);
WASM_IMPORT(double, asinh, double);
WASM_IMPORT(double, atan, double);
WASM_IMPORT(double, atan2, double, double);
WASM_IMPORT(double, atanh, double);
WASM_IMPORT(double, cbrt, double);
WASM_IMPORT(double, ceil, double);
// double copysign(double, double);
WASM_IMPORT(double, cos, double);
WASM_IMPORT(double, cosh, double);
// double erf(double);
// double erfc(double);
WASM_IMPORT(double, exp, double);
WASM_IMPORT(double, exp2, double);
WASM_IMPORT(double, expm1, double);
WASM_IMPORT(double, fabs, double);
WASM_IMPORT(double, fdim, double, double);
WASM_IMPORT(double, floor, double);
// double fma(double, double, double);
WASM_IMPORT(double, fmax, double, double);
WASM_IMPORT(double, fmin, double, double);
WASM_IMPORT(double, fmod, double, double);
// double frexp(double, int *);
WASM_IMPORT(double, hypot, double, double);
// int ilogb(double);
// double ldexp(double, int);
// double lgamma(double);
// long long llrint(double);
// long long llround(double);
WASM_IMPORT(double, log, double);
WASM_IMPORT(double, log10, double);
WASM_IMPORT(double, log1p, double);
WASM_IMPORT(double, log2, double);
// double logb(double);
// long lrint(double);
// long lround(double);
WASM_IMPORT(double, modf, double, double *);
WASM_IMPORT(double, nan, const char *);
// double nearbyint(double);
// double nextafter(double, double);
// double nexttoward(double, long double);
WASM_IMPORT(double, pow, double, double);
// double remainder(double, double);
// double remquo(double, double, int *);
// double rint(double);
WASM_IMPORT(double, round, double);
// double scalbln(double, long);
// double scalbn(double, int);
WASM_IMPORT(double, sin, double);
WASM_IMPORT(double, sinh, double);
WASM_IMPORT(double, sqrt, double);
WASM_IMPORT(double, tan, double);
WASM_IMPORT(double, tanh, double);
// double tgamma(double);
WASM_IMPORT(double, trunc, double);
