#pragma once

int isinf(double);
int isnan(double);

double acos(double);
double acosh(double);
double asin(double);
double asinh(double);
double atan(double);
double atan2(double, double);
double atanh(double);
double cbrt(double);
double ceil(double);
// double copysign(double, double);
double cos(double);
double cosh(double);
// double erf(double);
// double erfc(double);
double exp(double);
double exp2(double);
double expm1(double);
double fabs(double);
double fdim(double, double);
double floor(double);
// double fma(double, double, double);
double fmax(double, double);
double fmin(double, double);
double fmod(double, double);
// double frexp(double, int *);
double hypot(double, double);
// int ilogb(double);
double ldexp(double, int);
// double lgamma(double);
// long long llrint(double);
// long long llround(double);
double log(double);
double log10(double);
double log1p(double);
double log2(double);
// double logb(double);
// long lrint(double);
// long lround(double);
double modf(double, double *);
double nan(const char *);
// double nearbyint(double);
// double nextafter(double, double);
// double nexttoward(double, long double);
double pow(double, double);
// double remainder(double, double);
// double remquo(double, double, int *);
// double rint(double);
double round(double);
// double scalbln(double, long);
// double scalbn(double, int);
double sin(double);
double sinh(double);
double sqrt(double);
double tan(double);
double tanh(double);
// double tgamma(double);
double trunc(double);

float acosf(float);
float acoshf(float);
float asinf(float);
float asinhf(float);
float atanf(float);
float atan2f(float, float);
float atanhf(float);
float cbrtf(float);
float ceilf(float);
float cosf(float);
float coshf(float);
float expf(float);
float exp2f(float);
float expm1f(float);
float fabsf(float);
float fdimf(float, float);
float floorf(float);
float fmaxf(float, float);
float fminf(float, float);
float fmodf(float, float);
float hypotf(float, float);
float ldexpf(float, int);
float logf(float);
float log10f(float);
float log1pf(float);
float log2f(float);
float modff(float, float *);
float nanf(const char *);
float powf(float, float);
float roundf(float);
float sinf(float);
float sinhf(float);
float sqrtf(float);
float tanf(float);
float tanhf(float);
float truncf(float);
