export const math = {
  JS_acos: Math.acos,
  JS_acosh: Math.acosh,
  JS_asin: Math.asin,
  JS_asinh: Math.asinh,
  JS_atan: Math.atan,
  JS_atan2: Math.atan2,
  JS_atanh: Math.atanh,
  JS_cbrt: Math.cbrt,
  JS_ceil: Math.ceil,
  // JS_copysign:,
  JS_cos: Math.cos,
  JS_cosh: Math.cosh,
  // JS_erf:,
  // JS_erfc:,
  JS_exp: Math.exp,
  JS_exp2: (x) => Math.pow(2, x),
  JS_expm1: Math.expm1,
  JS_fabs: Math.abs,
  JS_fdim: (x, y) => {
    if (Number.isNaN(x))
      return x;
    if (Number.isNaN(y))
      return y;
    return x > y ? x - y : 0;
  },
  JS_floor: Math.floor,
  // JS_fma:,
  JS_fmax: Math.max,
  JS_fmin: Math.min,
  JS_fmod: (x, y) => x % y,
  // JS_frexp:,
  JS_hypot: Math.hypot,
  // JS_ilogb:,
  JS_ldexp: (x, exp) => x * Math.pow(2, exp),
  // JS_lgamma:,
  // JS_llrint:,
  // JS_llround:,
  JS_log: Math.log,
  JS_log10: Math.log10,
  JS_log1p: Math.log1p,
  JS_log2: Math.log2,
  // JS_logb:,
  // JS_lrint:,
  // JS_lround:,
  JS_modf: Math.modf,
  JS_nan: (s) => NaN,
  // JS_nearbyint:,
  // JS_nextafter:,
  // JS_nexttoward,
  JS_pow: Math.pow,
  // JS_remainder:,
  // JS_remquo:,
  // JS_rint:,
  JS_round: Math.round,
  // JS_scalbln:,
  // JS_scalbn:,
  JS_sin: Math.sin,
  JS_sinh: Math.sinh,
  JS_sqrt: Math.sqrt,
  JS_tan: Math.tan,
  JS_tanh: Math.tanh,
  // JS_tgamma:,
  JS_trunc: Math.trunc,
}
