export const math = {
  isnan: (x) => Number.isNaN(x),

  acos: Math.acos,
  acosh: Math.acosh,
  asin: Math.asin,
  asinh: Math.asinh,
  atan: Math.atan,
  atan2: Math.atan2,
  atanh: Math.atanh,
  cbrt: Math.cbrt,
  ceil: Math.ceil,
  // copysign:,
  cos: Math.cos,
  cosh: Math.cosh,
  // erf:,
  // erfc:,
  exp: Math.exp,
  exp2: (x) => Math.pow(2, x),
  expm1: Math.expm1,
  fabs: Math.abs,
  fdim: (x, y) => {
    if (math.isnan(x))
      return x;
    if (math.isnan(y))
      return y;
    return x > y ? x - y : 0;
  },
  floor: Math.floor,
  // fma:,
  fmax: Math.max,
  fmin: Math.min,
  fmod: (x, y) => x % y,
  // frexp:,
  hypot: Math.hypot,
  // ilogb:,
  // ldexp:,
  // lgamma:,
  // llrint:,
  // llround:,
  log: Math.log,
  log10: Math.log10,
  log1p: Math.log1p,
  log2: Math.log2,
  // logb:,
  // lrint:,
  // lround:,
  modf: Math.modf,
  nan: (s) => NaN,
  // nearbyint:,
  // nextafter:,
  // nexttoward,
  pow: Math.pow,
  // remainder:,
  // remquo:,
  // rint:,
  round: Math.round,
  // scalbln:,
  // scalbn:,
  sin: Math.sin,
  sinh: Math.sinh,
  sqrt: Math.sqrt,
  tan: Math.tan,
  tanh: Math.tanh,
  // tgamma:,
  trunc: Math.trunc,
}
