export const math = {
  // TODO check if these are correct
  isnan: (x) => Number.isNaN(x),
  isinf: (x) => x === Infinity || x === -Infinity,

  acos: Math.acos,
  acosh: Math.acosh,
  asin: Math.asin,
  asinh: Math.asinh,
  atan: Math.atan,
  atan2: Math.atan2,
  atanh: Math.atanh,
  cbrt: Math.cbrt,
  ceil: Math.ceil,
  // copysign:,
  cos: Math.cos,
  cosh: Math.cosh,
  // erf:,
  // erfc:,
  exp: Math.exp,
  exp2: (x) => Math.pow(2, x),
  expm1: Math.expm1,
  fabs: Math.abs,
  fdim: (x, y) => {
    if (math.isnan(x))
      return x;
    if (math.isnan(y))
      return y;
    return x > y ? x - y : 0;
  },
  floor: Math.floor,
  // fma:,
  fmax: Math.max,
  fmin: Math.min,
  fmod: (x, y) => x % y,
  // frexp:,
  hypot: Math.hypot,
  // ilogb:,
  ldexp: (x, exp) => x * Math.pow(2, exp),
  // lgamma:,
  // llrint:,
  // llround:,
  log: Math.log,
  log10: Math.log10,
  log1p: Math.log1p,
  log2: Math.log2,
  // logb:,
  // lrint:,
  // lround:,
  modf: Math.modf,
  nan: (s) => NaN,
  // nearbyint:,
  // nextafter:,
  // nexttoward,
  pow: Math.pow,
  // remainder:,
  // remquo:,
  // rint:,
  round: Math.round,
  // scalbln:,
  // scalbn:,
  sin: Math.sin,
  sinh: Math.sinh,
  sqrt: Math.sqrt,
  tan: Math.tan,
  tanh: Math.tanh,
  // tgamma:,
  trunc: Math.trunc,

  // floats
  acosf: Math.acos,
  acoshf: Math.acosh,
  asinf: Math.asin,
  asinhf: Math.asinh,
  atanf: Math.atan,
  atan2f: Math.atan2,
  atanhf: Math.atanh,
  cbrtf: Math.cbrt,
  ceilf: Math.ceil,
  cosf: Math.cos,
  coshf: Math.cosh,
  expf: Math.exp,
  exp2f: (x) => Math.pow(2, x),
  expm1f: Math.expm1,
  fabsf: Math.abs,
  fdimf: (x, y) => {
    if (math.isnan(x))
      return x;
    if (math.isnan(y))
      return y;
    return x > y ? x - y : 0;
  },
  floorf: Math.floor,
  fmaxf: Math.max,
  fminf: Math.min,
  fmodf: (x, y) => x % y,
  hypotf: Math.hypot,
  ldexpf: (x, exp) => x * Math.pow(2, exp),
  logf: Math.log,
  log10f: Math.log10,
  log1pf: Math.log1p,
  log2f: Math.log2,
  modff: Math.modf,
  nanf: (s) => NaN,
  powf: Math.pow,
  roundf: Math.round,
  sinf: Math.sin,
  sinhf: Math.sinh,
  sqrtf: Math.sqrt,
  tanf: Math.tan,
  tanhf: Math.tanh,
  truncf: Math.trunc,
}
